# Generated by Django 4.0.1 on 2022-02-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilMagasin',
        ),
    ]
